Add VSCode Integration
commit cb67ac83319ffdad21e2fe7ff176da8ab0333285
Author: Ignacio Vizzo <ignaciovizzo@gmail.com>
Date:   Mon Nov 7 17:09:13 2022 +0100

    Add copyright on json

commit ba294a28651110875fba00a0eac37ac488feb1c9
Author: Ignacio Vizzo <ignaciovizzo@gmail.com>
Date:   Mon Nov 7 17:07:28 2022 +0100

    Update README

commit 93d4e1b05d6df6a508893af2cd5f341588b05e14
Author: Ignacio Vizzo <ignaciovizzo@gmail.com>
Date:   Mon Nov 7 14:24:02 2022 +0100

    Add VSCode dev container integration

diff --git a/.base/Dockerfile b/.base/Dockerfile
--- a/.base/Dockerfile
+++ b/.base/Dockerfile
@@ -53,9 +53,13 @@ RUN sh -c \
 # Insall catkin tools
 RUN python3 -m pip install --user --upgrade catkin-tools
 
-# Finish setup
-RUN echo 'source /home/$USER_NAME/ros_ws/devel/setup.zsh 2>/dev/null || true' > /home/$USER_NAME/.zshrc_local
+# Finish setup, and cleanup custom nacho stuff
+RUN echo 'source /opt/ros/noetic/setup.zsh 2>/dev/null || true' > /home/$USER_NAME/.zshrc_local
+RUN echo 'source /home/$USER_NAME/ros_ws/devel/setup.zsh 2>/dev/null || true' >> /home/$USER_NAME/.zshrc_local
 RUN sed -i 's/\"fwalch\"/\"agnoster\"/' /home/$USER_NAME/.zshrc
+RUN sed -i 1,3d /home/$USER_NAME/.gitconfig
+
+# Add ROS entrypoint for zsh
 COPY ./ros_entrypoint.sh /
 ENTRYPOINT ["/ros_entrypoint.sh"]
 WORKDIR /home/$USER_NAME/ros_ws
